### ISSUE TITLE
pyglet.window.NoSuchConfigException

### ISSUE THREAD

**Issue by liwenssss** [vchoutas/smplx#4]
hello, thx your demo. When I want run demo.py, I got the error like this:
`Traceback (most recent call last):
  File "examples/demo.py", line 99, in <module>
    use_face_contour=use_face_contour)
  File "examples/demo.py", line 66, in main
    pyrender.Viewer(scene, use_raymond_lighting=True)
  File "/home/liwensh/anaconda3/lib/python3.7/site-packages/pyrender/viewer.py", line 347, in __init__
    self._init_and_start_app()
  File "/home/liwensh/anaconda3/lib/python3.7/site-packages/pyrender/viewer.py", line 997, in _init_and_start_app
    height=self._viewport_size[1])
  File "/home/liwensh/anaconda3/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py", line 170, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/liwensh/anaconda3/lib/python3.7/site-packages/pyglet/window/__init__.py", line 592, in __init__
    config = screen.get_best_config(config)
  File "/home/liwensh/anaconda3/lib/python3.7/site-packages/pyglet/canvas/base.py", line 197, in get_best_config
    raise window.NoSuchConfigException()  

pyglet.window.NoSuchConfigException
`
any suggestion can you give me about how to solve it?

**Comment by vchoutas** [comment]
@liwenssss I don't have any specific suggestions for pyglet. 
I just added an option for rendering with matplotlib or Open3D. Just pass --plotting-module='matplotlib' or --plotting_module='open3d' to demo.py.

**Comment by fenaux** [comment]
Hello,
Congratulations for your work ans many thanks for making it available !
I try to work with "google colab"
It seems I could install everything (including 
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt)

and then run
!python /content/smplx/examples/demo.py --model-folder /content/mydrive/smplx/models --plot-joints=True --plotting-module='matplotlib' --gender="neutral"

It seems the work ends proprely and I got the following message
SMPLX(
  Number of betas: 10
  Number of PCA components: 6
  Flat hand mean: False
  Gender: Neutral
  Expression Coefficients: 10
  Use face contour: False
  (vertex_joint_selector): VertexJointSelector()
)
Vertices shape = (10475, 3)
Joints shape = (127, 3)
<Figure size 640x480 with 1 Axes>

but no figure appears.

Am I doing something wrong or is this due to a problem with the new option you just opened ? (I get an error messages with pyrender and open3d).

thanks for your help

**Comment by wine3603** [comment]
I got the same error, how did you solve it ? @liwenssss 
matplotlib and open3d didn't work for me neither @vchoutas

**Comment by vchoutas** [comment]
This is a rendering issue and I cannot provide more help for this unfortunately, so I will be closing this.
