### ISSUE TITLE
Are there any GPU memory leaks in transfer_model code?

### ISSUE THREAD

**Issue by VVingerfly** [vchoutas/smplx#56]
I tried to use `transfer_model ` code to convert my human body parameters from SMPL to SMPL-X, but the GPU memory usage was continuously increasing as the fitting process proceeds. And finally a out_of_memory error occurred.

And I also tried to to run the provided sample code in the repo in a loop, and the GPU memory usage was also keeping increasing.

But I don't know how to fix it? Does anyone have a solution? 

Thanks a lot!

**Comment by zengwang430521** [comment]
I think this GPU memory leak may be caused by [Line143-146 in transfer_model.py](https://github.com/vchoutas/smplx/blob/f4206853a4746139f61bdcf58571f2cea0cbebad/transfer_model/transfer_model.py#L143-L146). You may refer to the [note of pytorch](https://pytorch.org/docs/stable/autograd.html).

I added a line: `for p in params: p.grad = None` after [line 176 in minimize.py](https://github.com/vchoutas/smplx/blob/f4206853a4746139f61bdcf58571f2cea0cbebad/transfer_model/optimizers/minimize.py#L76) and found that the GPU memory stop increasing.

**Comment by VVingerfly** [comment]
Hi, @zengwang430521  thanks for your reply. It indeed prevents the GPU memory from incresing. thank you!

Closing this now!
