### ISSUE TITLE
convert poses in the SMPL family

### ISSUE THREAD

**Issue by HenriMir** [vchoutas/smplx#63]
Hello and thanks for the SMPL repos!

I'm trying to convert poses between the different SMPL body models. I have tried the conversion implemented which works very well but convert mesh into mesh with optimisation which is a quite long process. 

Do you know how can we simply convert, for exemple, a SMPL-H with 156 dimensions into SMPL with 72 dimensions. 

Thanks for any help!

**Comment by MichaelJBlack** [comment]
SMPL-H and SMPL have the same pose and shape params (unlike SMPL-X and SMPL).  So you can simply ignore the hand pose params and use the other pose and shape parameters in SMPL.  It is that simple.

**Comment by HenriMir** [comment]
thanks a lot for the clarification, I'll close the issue then.

**Comment by AlyanQ** [comment]
Is there a way to convert shape/pose params between SMPL and SMPLX without converting between the two using your transfer models project? Thanks

**Comment by ZhengdiYu** [comment]
> converting between the two using your transfer

@AlyanQ Hi, did you find a solution ? I now have a set of mano pose and shape, and SMPL mano and shape, but it seems not correct to directly put them into SMPL-X model.

**Comment by ZhengdiYu** [comment]
> SMPL-H and SMPL have the same pose and shape params (unlike SMPL-X and SMPL). So you can simply ignore the hand pose params and use the other pose and shape parameters in SMPL. It is that simple.

in https://github.com/vchoutas/smplx/tree/master/transfer_model#smpl-to-smpl%2Bh 

it says:
`The repository contains code for converting model parameters of one model to another. Never copy parameters between the models. You will not get the same poses. SMPL, SMPL+H and SMPL-X shape spaces are NOT compatible, since each model is the result of a different training process. A more detailed explanation on how we extract correspondences between the models and the loss function used to estimate the parameters can be found [here](https://github.com/vchoutas/smplx/blob/master/transfer_model/docs/transfer.md).`

Which one should I follow? can I used smpl parameters (21, 3) for SMPL-H without hand and face? Just simply replace the SMPL-H's body pose?

**Comment by vchoutas** [comment]
@ZhengdiYu yes you can. There should not be a comma between SMPL and SMPL+H in the above text, but a slash. 
I will update the README.
